// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'drag-container': string;
  'drag-wrapper': string;
  'scal-tool-item': string;
  'scale-icon': string;
  'scale-num': string;
  'tool-item': string;
  toolbar: string;
}
export const cssExports: CssExports;
export default cssExports;
