// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'org-tree': string;
  'org-tree-container': string;
}
export const cssExports: CssExports;
export default cssExports;
