// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  children: string;
  'combine-nodes': string;
  'combine-tree-node': string;
  'epxand-btn': string;
  label: string;
  'label-inner': string;
  'tree-node': string;
}
export const cssExports: CssExports;
export default cssExports;
